import type { LessonStatus } from "@/types/lesson";

export const ESSENTIALS_LESSON_SLUGS = [
  "users-and-groups",
  "file-permissions",
  "ownership-and-sudo",
  "processes",
  "package-management",
  "environment-variables",
  "pipes-and-redirection",
  "searching-and-finding-files",
  "text-processing",
  "shell-basics",
  "introduction-to-bash-scripting",
  "linux-essentials-challenge",
] as const;

export type EssentialsLessonSlug = (typeof ESSENTIALS_LESSON_SLUGS)[number];

export type EssentialsLesson = {
  number: number;
  slug: EssentialsLessonSlug;
  title: string;
  description: string;
  duration: string;
  difficulty: string;
  status: LessonStatus;
  topics: readonly string[];
  href?: `/learn/essentials/${EssentialsLessonSlug}`;
};

export const essentialsPath = {
  slug: "essentials",
  number: 2,
  eyebrow: "STAGE 02",
  title: "Linux Essentials",
  badge: "INTERMEDIATE",
  description:
    "Build practical Linux skills by learning users, permissions, processes, packages, environment variables, and essential shell techniques.",
  level: "Intermediate",
  lessonCount: 12,
  estimatedTime: "About 4–6 hours",
  status: "available" as const satisfies LessonStatus,
  seoTitle: "Linux Essentials — Rean Linux",
  seoDescription:
    "Build practical Linux skills with users, permissions, processes, packages, environment variables, shell techniques, and Bash scripting.",
} as const;

export const essentialsLessons: readonly EssentialsLesson[] = [
  {
    number: 1,
    slug: "users-and-groups",
    title: "Users and Groups",
    description:
      "Learn how Linux identifies users and organizes them into groups.",
    duration: "15–20 min",
    difficulty: "Intermediate",
    status: "available",
    href: "/learn/essentials/users-and-groups",
    topics: [
      "Users",
      "User IDs",
      "Groups",
      "Group membership",
      "/etc/passwd",
      "/etc/group",
      "whoami",
      "id",
      "who",
      "groups",
    ],
  },
  {
    number: 2,
    slug: "file-permissions",
    title: "File Permissions",
    description: "Learn how Linux controls access to files and directories.",
    duration: "20 min",
    difficulty: "Intermediate",
    status: "coming-soon",
    topics: [
      "Read",
      "Write",
      "Execute",
      "User",
      "Group",
      "Others",
      "Permission notation",
      "ls -l",
      "chmod",
    ],
  },
  {
    number: 3,
    slug: "ownership-and-sudo",
    title: "Ownership and sudo",
    description: "Learn ownership and administrative privileges.",
    duration: "15 min",
    difficulty: "Intermediate",
    status: "coming-soon",
    topics: [
      "File ownership",
      "chown",
      "chgrp",
      "Root user",
      "sudo",
      "Why root access should be used carefully",
    ],
  },
  {
    number: 4,
    slug: "processes",
    title: "Processes",
    description: "Learn what programs are doing while they run.",
    duration: "20 min",
    difficulty: "Intermediate",
    status: "coming-soon",
    topics: [
      "What is a process?",
      "Process IDs",
      "ps",
      "top",
      "htop",
      "kill",
      "Foreground/background concepts",
    ],
  },
  {
    number: 5,
    slug: "package-management",
    title: "Package Management",
    description:
      "Understand how Linux installs and manages software across distributions.",
    duration: "20 min",
    difficulty: "Intermediate",
    status: "coming-soon",
    topics: [
      "Packages",
      "Package repositories",
      "Installing software",
      "Updating packages",
      "Removing packages",
      "apt",
      "Basic package lifecycle",
    ],
  },
  {
    number: 6,
    slug: "environment-variables",
    title: "Environment Variables",
    description:
      "Learn how the shell and applications use environment variables.",
    duration: "15 min",
    difficulty: "Intermediate",
    status: "coming-soon",
    topics: [
      "What environment variables are",
      "env",
      "printenv",
      "echo",
      "PATH",
      "HOME",
      "USER",
      "Setting variables",
      "Exporting variables",
    ],
  },
  {
    number: 7,
    slug: "pipes-and-redirection",
    title: "Pipes and Redirection",
    description: "Learn how commands can work together.",
    duration: "25 min",
    difficulty: "Intermediate",
    status: "coming-soon",
    topics: [
      "Standard input",
      "Standard output",
      "Standard error",
      ">",
      ">>",
      "<",
      "|",
      "tee",
    ],
  },
  {
    number: 8,
    slug: "searching-and-finding-files",
    title: "Searching and Finding Files",
    description: "Learn how to locate files and search through content.",
    duration: "20 min",
    difficulty: "Intermediate",
    status: "coming-soon",
    topics: [
      "find",
      "locate",
      "which",
      "grep",
      "Searching filenames",
      "Searching file contents",
      "Basic search patterns",
    ],
  },
  {
    number: 9,
    slug: "text-processing",
    title: "Text Processing",
    description:
      "Learn the basic command-line tools used to inspect and manipulate text.",
    duration: "20 min",
    difficulty: "Intermediate",
    status: "coming-soon",
    topics: ["head", "tail", "sort", "uniq", "wc", "cut", "tr"],
  },
  {
    number: 10,
    slug: "shell-basics",
    title: "Shell Basics",
    description: "Understand how the shell interprets commands.",
    duration: "25 min",
    difficulty: "Intermediate",
    status: "coming-soon",
    topics: [
      "Shell vs terminal",
      "Bash",
      "Command expansion",
      "Quoting",
      "Variables",
      "Wildcards",
      "Command history",
      "Aliases",
    ],
  },
  {
    number: 11,
    slug: "introduction-to-bash-scripting",
    title: "Introduction to Bash Scripting",
    description: "Create simple reusable shell scripts.",
    duration: "40 min",
    difficulty: "Intermediate",
    status: "coming-soon",
    topics: [
      "Shebang",
      "Variables",
      "Arguments",
      "Exit codes",
      "Conditions",
      "Loops",
      "Functions",
      "Executable scripts",
    ],
  },
  {
    number: 12,
    slug: "linux-essentials-challenge",
    title: "Linux Essentials Challenge",
    description:
      "A practical capstone that combines navigation, permissions, processes, packages, pipes, searching, and shell scripting.",
    duration: "45 min",
    difficulty: "Intermediate",
    status: "coming-soon",
    topics: [
      "Filesystem navigation",
      "Files",
      "Permissions",
      "Users",
      "Processes",
      "Packages",
      "Environment variables",
      "Pipes",
      "Searching",
      "Shell scripting",
    ],
  },
];
