import type { LessonStatus } from "@/types/lesson";

export const ESSENTIALS_LESSON_SLUGS = [
  "users-and-groups",
  "file-permissions",
  "ownership-and-sudo",
  "processes",
  "package-management",
  "environment-variables",
  "pipes-and-redirection",
  "searching-and-finding-files",
  "text-processing",
  "shell-basics",
  "bash-scripting",
  "linux-essentials-challenge",
] as const;

export type EssentialsLessonSlug = (typeof ESSENTIALS_LESSON_SLUGS)[number];

export type EssentialsLesson = {
  number: number;
  slug: EssentialsLessonSlug;
  title: string;
  description: string;
  duration: string;
  difficulty: string;
  status: LessonStatus;
  topics: readonly string[];
  href?: `/learn/essentials/${EssentialsLessonSlug}`;
};

export const essentialsPath = {
  slug: "essentials",
  number: 2,
  eyebrow: "STAGE 02",
  title: "Linux Essentials",
  badge: "INTERMEDIATE",
  description:
    "Build practical Linux skills by learning users, permissions, processes, packages, environment variables, and essential shell techniques.",
  level: "Intermediate",
  lessonCount: 12,
  estimatedTime: "About 4–6 hours",
  status: "available" as const satisfies LessonStatus,
  seoTitle: "Linux Essentials — Rean Linux",
  seoDescription:
    "Build practical Linux skills with users, permissions, processes, packages, environment variables, shell techniques, and Bash scripting.",
} as const;

export const essentialsLessons: readonly EssentialsLesson[] = [
  {
    number: 1,
    slug: "users-and-groups",
    title: "Users and Groups",
    description:
      "Learn how Linux identifies users and organizes them into groups.",
    duration: "15–20 min",
    difficulty: "Intermediate",
    status: "available",
    href: "/learn/essentials/users-and-groups",
    topics: [
      "Users",
      "User IDs",
      "Groups",
      "Group membership",
      "/etc/passwd",
      "/etc/group",
      "whoami",
      "id",
      "who",
      "groups",
    ],
  },
  {
    number: 2,
    slug: "file-permissions",
    title: "File Permissions",
    description: "Learn how Linux controls access to files and directories.",
    duration: "20–25 min",
    difficulty: "Intermediate",
    status: "available",
    href: "/learn/essentials/file-permissions",
    topics: [
      "Read",
      "Write",
      "Execute",
      "User",
      "Group",
      "Others",
      "Permission notation",
      "ls -l",
      "chmod",
    ],
  },
  {
    number: 3,
    slug: "ownership-and-sudo",
    title: "Ownership and sudo",
    description: "Learn ownership and administrative privileges.",
    duration: "20–25 min",
    difficulty: "Intermediate",
    status: "available",
    href: "/learn/essentials/ownership-and-sudo",
    topics: [
      "File ownership",
      "chown",
      "chgrp",
      "Root user",
      "sudo",
      "Why root access should be used carefully",
    ],
  },
  {
    number: 4,
    slug: "processes",
    title: "Processes",
    description:
      "Understand what processes are, how Linux identifies them, how to inspect them, and how to stop them safely.",
    duration: "20–25 min",
    difficulty: "Intermediate",
    status: "available",
    href: "/learn/essentials/processes",
    topics: [
      "What is a process?",
      "Process IDs",
      "Parent and child processes",
      "ps",
      "top",
      "kill",
      "SIGTERM vs SIGKILL",
      "Foreground/background concepts",
    ],
  },
  {
    number: 5,
    slug: "package-management",
    title: "Package Management",
    description:
      "Learn how Linux installs, updates, searches, and removes software using package managers and repositories.",
    duration: "20–25 min",
    difficulty: "Intermediate",
    status: "available",
    href: "/learn/essentials/package-management",
    topics: [
      "Packages",
      "Package repositories",
      "Installing software",
      "Updating packages",
      "Removing packages",
      "apt",
      "Basic package lifecycle",
    ],
  },
  {
    number: 6,
    slug: "environment-variables",
    title: "Environment Variables",
    description:
      "Understand how Linux stores environment settings, how to inspect and change them, and why variables like PATH and HOME matter.",
    duration: "20–25 min",
    difficulty: "Intermediate",
    status: "available",
    href: "/learn/essentials/environment-variables",
    topics: [
      "What environment variables are",
      "env",
      "printenv",
      "echo",
      "PATH",
      "HOME",
      "USER",
      "Setting variables",
      "Exporting variables",
    ],
  },
  {
    number: 7,
    slug: "pipes-and-redirection",
    title: "Pipes and Redirection",
    description:
      "Learn how to connect commands with pipes and control where command input and output go.",
    duration: "20–25 min",
    difficulty: "Intermediate",
    status: "available",
    href: "/learn/essentials/pipes-and-redirection",
    topics: [
      "Standard input",
      "Standard output",
      "Standard error",
      ">",
      ">>",
      "<",
      "|",
      "2>",
      "2>&1",
    ],
  },
  {
    number: 8,
    slug: "searching-and-finding-files",
    title: "Searching and Finding Files",
    description:
      "Learn how to locate files, search their contents, and combine search commands effectively.",
    duration: "20–25 min",
    difficulty: "Intermediate",
    status: "available",
    href: "/learn/essentials/searching-and-finding-files",
    topics: [
      "find",
      "grep",
      "Searching filenames",
      "Searching file contents",
      "Wildcard patterns",
      "Recursive search",
      "Combining find and grep",
    ],
  },
  {
    number: 9,
    slug: "text-processing",
    title: "Text Processing",
    description:
      "Learn how to inspect, filter, count, sort, and transform text using common Linux command-line tools.",
    duration: "25–30 min",
    difficulty: "Intermediate",
    status: "available",
    href: "/learn/essentials/text-processing",
    topics: [
      "cat",
      "wc",
      "sort",
      "uniq",
      "cut",
      "head",
      "tail",
      "Text pipelines",
      "Combining filters",
    ],
  },
  {
    number: 10,
    slug: "shell-basics",
    title: "Shell Basics",
    description:
      "Understand how a shell interprets commands, handles quotes and variables, and combines commands into useful workflows.",
    duration: "25–30 min",
    difficulty: "Intermediate",
    status: "available",
    href: "/learn/essentials/shell-basics",
    topics: [
      "Shell vs terminal",
      "Bash",
      "Command structure",
      "Quoting",
      "Escaping",
      "Variables",
      "Command substitution",
      "Exit status",
      "; && ||",
    ],
  },
  {
    number: 11,
    slug: "bash-scripting",
    title: "Introduction to Bash Scripting",
    description:
      "Learn how to automate repetitive tasks with Bash scripts using variables, command sequences, conditions, and loops.",
    duration: "30–35 min",
    difficulty: "Intermediate",
    status: "available",
    href: "/learn/essentials/bash-scripting",
    topics: [
      "What is a Bash script?",
      "Shebang",
      "Creating scripts",
      "Variables",
      "read",
      "Command sequences",
      "if / else",
      "for loops",
      "while loops",
    ],
  },
  {
    number: 12,
    slug: "linux-essentials-challenge",
    title: "Linux Essentials Challenge",
    description:
      "Put your Linux skills to the test with practical challenges covering commands, permissions, processes, packages, and shell scripting.",
    duration: "35–45 min",
    difficulty: "Intermediate",
    status: "available",
    href: "/learn/essentials/linux-essentials-challenge",
    topics: [
      "Users and groups",
      "File permissions",
      "Ownership and sudo",
      "Processes",
      "Packages",
      "Environment variables",
      "Pipes and redirection",
      "Searching and finding files",
      "Text processing",
      "Shell basics",
      "Bash scripting",
    ],
  },
];
